module.exports = {
  apps: [
    {
      name: "cloudflared",
      script: "/usr/local/bin/cloudflared",
      args: "tunnel --config /home/apple/.cloudflared/config.yml run",
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      time: true,
    },
    {
      name: "darkblueapi-service",
      cwd: "/home/apple/DARKBLUE-DRAFTKIT-PROJECT/valuation-api",
      script: "server.js",
      autorestart: true,
      max_restarts: 20,
      restart_delay: 3000,
      time: true,
      env: {
        NODE_ENV: "production",
        PORT: "3006",
      },
    },
    {
      name: "darkbluevalue-site",
      cwd: "/home/apple/DARKBLUE-DRAFTKIT-PROJECT",
      script: "scripts/serve-static.cjs",
      args: "--root valuation-site --host 127.0.0.1 --port 3004 --spa",
      autorestart: true,
      max_restarts: 20,
      restart_delay: 3000,
      time: true,
    },
    {
      name: "draftkit-app-api",
      cwd: "/home/apple/DARKBLUE-DRAFTKIT-PROJECT/draftkit-api",
      script: "server.js",
      autorestart: true,
      max_restarts: 20,
      restart_delay: 3000,
      time: true,
      env: {
        NODE_ENV: "production",
        PORT: "3002",
        TRUST_PROXY_HOPS: "1",
        ALLOWED_ORIGINS: "https://draft.anythingavenue.com",
        PASSWORD_RESET_BASE_URL: "https://draft.anythingavenue.com",
        VALUATION_API_BASE: "http://127.0.0.1:3006",
      },
    },
    {
      name: "draftkit-web",
      cwd: "/home/apple/DARKBLUE-DRAFTKIT-PROJECT",
      script: "scripts/serve-static.cjs",
      args: "--root draftkit-web/dist --host 127.0.0.1 --port 3003 --spa",
      autorestart: true,
      max_restarts: 20,
      restart_delay: 3000,
      time: true,
    },
  ],
};
